package com.dom1.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.io.Serializable;

/**
 * null
 * @TableName customer
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class Customer implements Serializable {
    /**
     * id
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private Long id;

    /**
     * 客户名称
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private String name;

    /**
     * 联系人
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private String contact;

    /**
     * 电话号码
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private String telephone;

    /**
     * 邮箱地址
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private String email;

    /**
     * 备注
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated 2021-07-01 21:57:00
     */
    private static final long serialVersionUID = 1L;
}